### ISSUE TITLE
Tests make us better

### ISSUE THREAD

**Issue by Chu127001** [Chu127001/prodTest#1]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x36626992f7e42bbef3195aca2477a88d09b5f58534c055d7ee331291caae5635](https://etherscan.io/tx/0x36626992f7e42bbef3195aca2477a88d09b5f58534c055d7ee331291caae5635)

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x55df1fd7e3b2f42fdbbb13995c2dce7eb5d3b928c1bbc3a900f13fa4c4e7fd52](https://etherscan.io/tx/0x55df1fd7e3b2f42fdbbb13995c2dce7eb5d3b928c1bbc3a900f13fa4c4e7fd52)

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Contract address: [0xd5d8dfb6f358834b85afbb718fb191fe8c2fb5ea](https://etherscan.io/address/0xd5d8dfb6f358834b85afbb718fb191fe8c2fb5ea)
![QR Code](https://openbounty.status.im/qr/Chu127001/prodTest/bounty/1/eed7644e978649e93c4481d6a3bdad743ce8e67fbe8accd1bd881d87c01c6de4/qr.png)
Network: Mainnet
To claim this bounty sign up at [https://openbounty.status.im](https://openbounty.status.im) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send ETH or ERC20/ERC223 tokens to the contract address.
